"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from smartcar import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ChargeAmmeter:
    r"""returns the amperage of the charger measured by the vehicle."""
    amperage: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('amperage'), 'exclude': lambda f: f is None }})
    r"""The amperage of the charger measured by the vehicle."""
    

