"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import batchresponse as shared_batchresponse
from typing import Optional


@dataclasses.dataclass
class BatchRequest:
    
    vehicle_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'vehicle_id', 'style': 'simple', 'explode': False }})
    request_body: Optional[list[str]] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    

@dataclasses.dataclass
class BatchResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    batch_response: Optional[shared_batchresponse.BatchResponse] = dataclasses.field(default=None)
    r"""A list of responses from multiple Smartcar endpoints"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    