"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import batterycapacity as shared_batterycapacity
from typing import Optional



@dataclasses.dataclass
class GetBatteryCapacityRequest:
    vehicle_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'vehicle_id', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class GetBatteryCapacityResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    battery_capacity: Optional[shared_batterycapacity.BatteryCapacity] = dataclasses.field(default=None)
    r"""return EV Battery Capacity reading"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

