"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import userinfo as shared_userinfo
from typing import Optional



@dataclasses.dataclass
class GetInfoResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    user_info: Optional[shared_userinfo.UserInfo] = dataclasses.field(default=None)
    r"""return User's information"""
    

