"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import location as shared_location
from typing import Optional


@dataclasses.dataclass
class GetLocationRequest:
    
    vehicle_id: Optional[str] = dataclasses.field(default=None, metadata={'path_param': { 'field_name': 'vehicle_id', 'style': 'simple', 'explode': False }})  
    

@dataclasses.dataclass
class GetLocationResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    location: Optional[shared_location.Location] = dataclasses.field(default=None)
    r"""A list of vehicles"""  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    