"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import odometer as shared_odometer
from typing import Optional


@dataclasses.dataclass
class GetOdometerRequest:
    
    vehicle_id: Optional[str] = dataclasses.field(default=None, metadata={'path_param': { 'field_name': 'vehicle_id', 'style': 'simple', 'explode': False }})  
    

@dataclasses.dataclass
class GetOdometerResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    odometer: Optional[shared_odometer.Odometer] = dataclasses.field(default=None)
    r"""return odometer reading"""  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    