"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import chargewattage as shared_chargewattage
from typing import Optional


@dataclasses.dataclass
class GetTeslaWattmeterRequest:
    
    vehicle_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'vehicle_id', 'style': 'simple', 'explode': False }})
    

@dataclasses.dataclass
class GetTeslaWattmeterResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    charge_wattage: Optional[shared_chargewattage.ChargeWattage] = dataclasses.field(default=None)
    r"""returns the wattage of the charger measured by the vehicle."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    