"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import compass as shared_compass
from typing import Optional


@dataclasses.dataclass
class GetTeslaCompassRequest:
    
    vehicle_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'vehicle_id', 'style': 'simple', 'explode': False }})
    

@dataclasses.dataclass
class GetTeslaCompassResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    compass: Optional[shared_compass.Compass] = dataclasses.field(default=None)
    r"""returns the compass heading of a Tesla."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    