"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import speed as shared_speed
from typing import Optional



@dataclasses.dataclass
class GetTeslaSpeedRequest:
    vehicle_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'vehicle_id', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class GetTeslaSpeedResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    speed: Optional[shared_speed.Speed] = dataclasses.field(default=None)
    r"""returns the speed of a Tesla."""
    

