"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import temperature as shared_temperature
from typing import Optional


@dataclasses.dataclass
class GetTeslaExteriorTemperatureRequest:
    
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    

@dataclasses.dataclass
class GetTeslaExteriorTemperatureResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    temperature: Optional[shared_temperature.Temperature] = dataclasses.field(default=None)
    r"""returns the exterior temperature of a Tesla."""
    