"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import vininfo as shared_vininfo
from typing import Optional


@dataclasses.dataclass
class GetVinRequest:
    
    vehicle_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'vehicle_id', 'style': 'simple', 'explode': False }})
    

@dataclasses.dataclass
class GetVinResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    vin_info: Optional[shared_vininfo.VinInfo] = dataclasses.field(default=None)
    r"""return EV Battery Capacity reading"""
    