"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import securityaction as shared_securityaction
from ..shared import successresponse as shared_successresponse
from typing import Optional


@dataclasses.dataclass
class LockUnlockRequest:
    vehicle_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'vehicle_id', 'style': 'simple', 'explode': False }})
    security_action: Optional[shared_securityaction.SecurityAction] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class LockUnlockResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    success_response: Optional[shared_successresponse.SuccessResponse] = dataclasses.field(default=None)
    r"""return Compatibility"""
    

