"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import securityaction as shared_securityaction
from ..shared import securityresponse as shared_securityresponse
from typing import Optional


@dataclasses.dataclass
class LockUnlockRequest:
    
    security_action: Optional[shared_securityaction.SecurityAction] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})  
    vehicle_id: Optional[str] = dataclasses.field(default=None, metadata={'path_param': { 'field_name': 'vehicle_id', 'style': 'simple', 'explode': False }})  
    

@dataclasses.dataclass
class LockUnlockResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    security_response: Optional[shared_securityresponse.SecurityResponse] = dataclasses.field(default=None)
    r"""return Compatibility"""  
    