"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import chargeammeter as shared_chargeammeter
from ..shared import successresponse as shared_successresponse
from typing import Optional


@dataclasses.dataclass
class SetTeslaAmmeterRequest:
    vehicle_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'vehicle_id', 'style': 'simple', 'explode': False }})
    charge_ammeter: Optional[shared_chargeammeter.ChargeAmmeter] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class SetTeslaAmmeterResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    success_response: Optional[shared_successresponse.SuccessResponse] = dataclasses.field(default=None)
    r"""returns the amperage of the charger measured by the vehicle."""
    

