"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import chargeaction as shared_chargeaction
from ..shared import successresponse as shared_successresponse
from typing import Optional



@dataclasses.dataclass
class StartStopChargeRequest:
    vehicle_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'vehicle_id', 'style': 'simple', 'explode': False }})
    charge_action: Optional[shared_chargeaction.ChargeAction] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class StartStopChargeResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    success_response: Optional[shared_successresponse.SuccessResponse] = dataclasses.field(default=None)
    r"""return Success Response"""
    

