"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from .sdkconfiguration import SDKConfiguration
from smartcar import utils
from smartcar.models import errors, operations, shared
from typing import Optional

class Compatibility:
    r"""Operations about compatibility"""
    sdk_configuration: SDKConfiguration

    def __init__(self, sdk_config: SDKConfiguration) -> None:
        self.sdk_configuration = sdk_config
        
    
    def list_compatibility(self, country: Optional[str] = None, scope: Optional[str] = None, vin: Optional[str] = None) -> operations.ListCompatibilityResponse:
        r"""Compatibility
        In the US, compatibility will return a breakdown by scope of what a car is capable of. In Europe, the check is based on the make of the car so will return only a `true` or `false`

        The Compatibility API lets developers determine whether a given vehicle is compatible with Smartcar and whether it is capable of the features their application requires. Using this endpoint, developers can determine whether specific vehicles are eligible before sending a user through Smartcar Connect.

        A compatible vehicle is one that:
        1. Has the hardware required for internet connectivity
        2. Belongs to the makes and models Smartcar is compatible with in the vehicle's country

        A vehicle is capable of given feature if:
        1. The vehicle supports the feature (e.g., a Ford Escape supports /fuel but a Mustang Mach-e does not)
        2. Smartcar supports the feature for the vehicle's make

        Note: The Compatibility API is currently available for vehicles sold in the United States. For other countries, please contact us to request early access. Our initial release for vehicles sold outside of the United States only supports checking compatibility. It does not yet support checking `capabilities`.

        |  Name 	|Type   	|Boolean   	|
        |---	|---	|---	|
        |  compatible|   boolean|  `true` if the vehicle is likely compatible.*, `false` otherwise.| 
        reason|   string \| null|  One of the enum values described below if compatible is `false`, `null` otherwise.|
        | capabilities|   array| An array containing the set of endpoints that the provided scope value can provide authorization for. This array will be empty if `compatible` is false|
        | capabilities[].permission|   string|One of the permissions provided in the scope parameter.|
        | capabilities[].endpoint|   string| One of the endpoints that the permission authorizes access to.|
        | capabilities[].capable|   boolean|`true` if the vehicle is likely capable of this feature.*, `false` otherwise.|
        | capabilities[].reason|   string \| null|One of the enum values described below if capable is `false`, `null` otherwise.|

        __Note__: The compatibility of a vehicle depends on many factors including its make, model, model year, trim, package, and head unit. The Smartcar Compatibility API is optimized to return false positives rather than false negatives.

        __Enum Values__

        |  Parameter 	|Value   	|Description   	|
        |---	|---	|---	|
        |  reason|   VEHICLE_NOT_COMPATIBLE|  The vehicle does not have the hardware required for internet connectivity.|
        |  |   MAKE_NOT_COMPATIBLE|  Smartcar is not yet compatible with the vehicle's make in the specified country.|
        |  capabilities[].reason|   VEHICLE_NOT_CAPABLE|  TThe vehicle does not support this feature.|
        |  |   SMARTCAR_NOT_CAPABLE|  Smartcar is not capable of supporting the given feature on the vehicle's make.|
        """
        request = operations.ListCompatibilityRequest(
            country=country,
            scope=scope,
            vin=vin,
        )
        
        base_url = utils.template_url(*self.sdk_configuration.get_server_details())
        
        url = base_url + '/compatibility'
        headers = {}
        query_params = utils.get_query_params(operations.ListCompatibilityRequest, request)
        headers['Accept'] = 'application/json'
        headers['user-agent'] = self.sdk_configuration.user_agent
        
        client = self.sdk_configuration.security_client
        
        http_res = client.request('GET', url, params=query_params, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.ListCompatibilityResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.CompatibilityResponse])
                res.compatibility_response = out
            else:
                raise errors.SDKError(f'unknown content-type received: {content_type}', http_res.status_code, http_res.text, http_res)
        elif http_res.status_code >= 400 and http_res.status_code < 500 or http_res.status_code >= 500 and http_res.status_code < 600:
            raise errors.SDKError('API error occurred', http_res.status_code, http_res.text, http_res)

        return res

    