"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from .sdkconfiguration import SDKConfiguration
from smartcar import utils
from smartcar.models import errors, operations, shared
from typing import List, Optional

class VehicleManagement:
    sdk_configuration: SDKConfiguration

    def __init__(self, sdk_config: SDKConfiguration) -> None:
        self.sdk_configuration = sdk_config
        
    
    def delete_management_vehicle_connections(self, security: operations.DeleteManagementVehicleConnectionsSecurity, user_id: Optional[str] = None, vehicle_id: Optional[str] = None, server_url: Optional[str] = None) -> operations.DeleteManagementVehicleConnectionsResponse:
        r"""Delete vehicle connections by user_id or vehicle_id
        Delete all connections by vehicle or user ID.
        """
        request = operations.DeleteManagementVehicleConnectionsRequest(
            user_id=user_id,
            vehicle_id=vehicle_id,
        )
        
        base_url = utils.template_url(operations.DELETE_MANAGEMENT_VEHICLE_CONNECTIONS_SERVERS[0], {
        })
        if server_url is not None:
            base_url = server_url
        
        url = base_url + '/management/connections'
        headers = {}
        query_params = utils.get_query_params(operations.DeleteManagementVehicleConnectionsRequest, request)
        headers['Accept'] = 'application/json'
        headers['user-agent'] = self.sdk_configuration.user_agent
        
        client = utils.configure_security_client(self.sdk_configuration.client, security)
        
        http_res = client.request('DELETE', url, params=query_params, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.DeleteManagementVehicleConnectionsResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[List[shared.DeletedConnection]])
                res.deleted_connections_response = out
            else:
                raise errors.SDKError(f'unknown content-type received: {content_type}', http_res.status_code, http_res.text, http_res)
        elif http_res.status_code >= 400 and http_res.status_code < 500 or http_res.status_code >= 500 and http_res.status_code < 600:
            raise errors.SDKError('API error occurred', http_res.status_code, http_res.text, http_res)

        return res

    
    def get_management_vehicle_connections(self, security: operations.GetManagementVehicleConnectionsSecurity, cursor: Optional[int] = None, limit: Optional[int] = None, user_id: Optional[str] = None, vehicle_id: Optional[str] = None, server_url: Optional[str] = None) -> operations.GetManagementVehicleConnectionsResponse:
        r"""Retrieve vehicle connections
        Returns a paged list of all the vehicles that are connected to the application associated with the management API token used sorted in descending order by connection date.
        """
        request = operations.GetManagementVehicleConnectionsRequest(
            cursor=cursor,
            limit=limit,
            user_id=user_id,
            vehicle_id=vehicle_id,
        )
        
        base_url = utils.template_url(operations.GET_MANAGEMENT_VEHICLE_CONNECTIONS_SERVERS[0], {
        })
        if server_url is not None:
            base_url = server_url
        
        url = base_url + '/management/connections'
        headers = {}
        query_params = utils.get_query_params(operations.GetManagementVehicleConnectionsRequest, request)
        headers['Accept'] = 'application/json'
        headers['user-agent'] = self.sdk_configuration.user_agent
        
        client = utils.configure_security_client(self.sdk_configuration.client, security)
        
        http_res = client.request('GET', url, params=query_params, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.GetManagementVehicleConnectionsResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.ConnectionsResponse])
                res.connections_response = out
            else:
                raise errors.SDKError(f'unknown content-type received: {content_type}', http_res.status_code, http_res.text, http_res)
        elif http_res.status_code >= 400 and http_res.status_code < 500 or http_res.status_code >= 500 and http_res.status_code < 600:
            raise errors.SDKError('API error occurred', http_res.status_code, http_res.text, http_res)

        return res

    